# Generated by Django 5.0.1 on 2024-02-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolioApp', '0002_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('link', models.URLField(max_length=150)),
                ('logo', models.TextField(max_length=50)),
            ],
        ),
    ]
