# Generated by Django 5.0.1 on 2024-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolioApp', '0004_myportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio',
            name='technology',
            field=models.CharField(default='', max_length=50),
        ),
    ]
